DROP DATABASE IF EXISTS fresher;
CREATE DATABASE fresher;
USE fresher;

DROP TABLE IF EXISTS Trainee;
CREATE TABLE Trainee(

Trainee_ID		INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
Full_Name		NVARCHAR(50) NOT NULL,
Birth_Date		DATE NOT NULL,
Gender			ENUM('MALE','FEMALE','UNKNOWN'),
ET_IQ			INT UNSIGNED CHECK (ET_IQ<=20),
ET_Gmath		INT UNIQUE CHECK (ET_Gmath<=20),
ET_English		INT  CHECK (ET_English<=50),
Training_Class	NVARCHAR(50) NOT NULL,
Evaluation		NVARCHAR(50) NOT NULL 
);